<?php
/** @var Tree $block */

use GardenLawn\MediaGallery\Block\Adminhtml\Gallery\Tree;

?>
<div class="gallery-tree-container">
    <div id="gallery-tree"></div>
</div>

<script>
    require(['jquery', 'jstree'], function($) {
        let tree = $('#gallery-tree');

        tree.on('changed.jstree', function (e, data) {
                if (data.selected.length) {
                    var selectedId = data.instance.get_node(data.selected[0]).id;
                    var filterValue = (selectedId === 'root') ? '' : selectedId;
                    $('body').trigger('gallery:filter:update', [filterValue]);
                }
            })
            .jstree({
                'core': {
                    // Load data dynamically via AJAX
                    'data': {
                        'url': '<?= $block->escapeUrl($block->getUrl('gardenlawn_mediagallery/gallery/treedata')) ?>',
                        'dataType': 'json'
                    },
                    'check_callback': true, // Allows for dynamic modifications
                    'themes': {
                        'name': 'default',
                        'dots': true,
                        'icons': true
                    }
                },
                'plugins': ['wholerow']
            });

        // Listen for the reload trigger
        $('body').on('gallery:tree:reload', function() {
            tree.jstree(true).refresh();
        });
    });
</script>
